{% set name = "blik" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/blik-{{ version }}.tar.gz
  sha256: 018bd3028238c0ba8d0a8df3ef3681a82852349583a3661ea7cc7a117d554060

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.9
  run:
    - cryohub >=0.5.0
    - cryotypes >=0.2.0
    - dask-core
    - einops
    - magicgui >=0.4.0
    - morphosamplers >=0.0.5
    - napari
    - numpy
    - pandas
    - python >=3.9
    - scikit-image  # Not listed as requirement
    - scipy

test:
  imports:
    - blik
    - blik.reader
    - blik.utils
    - blik.writer
    - blik.widgets.file_reader
    - blik.widgets.filter
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/blik
  summary: Python tool for visualising and interacting with cryo-ET and subtomogram averaging data.
  license: GPL-3.0-only
  license_file: LICENSE
  dev_url: https://github.com/gutsche-lab/blik

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
