{% set name = "blik" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/blik-{{ version }}.tar.gz
  sha256: 018bd3028238c0ba8d0a8df3ef3681a82852349583a3661ea7cc7a117d554060

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - cryohub >=0.3.2
    - cryotypes
    - dask-core
    - magicgui >=0.4.0
    - naaf >=0.2.2
    - napari
    - numpy
    - pandas
    - python >=3.8
    - scikit-image
    - scipy

test:
  imports:
    - blik
    - blik.reader
    - blik.utils
    - blik.writer
    - blik.widgets.file_reader
    - blik.widgets.filter
  commands:
    - pip list
    # - pip check  # This can uncommented when naaf relaxes the dependencies
  requires:
    - pip

about:
  home: https://github.com/gutsche-lab/blik
  summary: Python tool for visualising and interacting with cryo-ET and subtomogram averaging data.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
