{% set name = "blik" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/blik-{{ version }}.tar.gz
  sha256: f37f026bf47fe20dc0fc5ca567138eb7d69809513bb09f09c947ef0430cea7d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - dask-core
    - magicgui >=0.4.0
    - naaf >=0.2.2
    - numpy
    - pandas
    - python >=3.8
    - scipy
    - scikit-image
    - napari

test:
  imports:
    - blik
    - blik.reader
    - blik.widgets.file_reader
    - blik.widgets.filter
    - blik.widgets.volume_selector
  commands:
    - pip list
    # - pip check  # This can uncommented when naaf relaxes the dependencies
  requires:
    - pip

about:
  home: https://github.com/gutsche-lab/blik
  summary: Python tool for visualising and interacting with cryo-ET and subtomogram averaging data.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
